FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/
RUN npm install

COPY . .

CMD npx prisma generate && \
    npx prisma migrate deploy --schema=./prisma/schema.prisma || \
    npx prisma db push --schema=./prisma/schema.prisma && \
    npx prisma db seed --schema=./prisma/schema.prisma || true